import type { BadgeAnimal } from './types';

export const DAYLIGHT_ANIMALS: BadgeAnimal[] = [
  { name: 'Clownfish', emoji: '🐠', zone: 'daylight' },
  { name: 'Blue Tang', emoji: '🐟', zone: 'daylight' },
  { name: 'Sea Turtle', emoji: '🐢', zone: 'daylight' },
  { name: 'Dolphin', emoji: '🐬', zone: 'daylight' },
  { name: 'Sea Otter', emoji: '🦦', zone: 'daylight' },
  { name: 'Starfish', emoji: '⭐', zone: 'daylight' },
  { name: 'Seahorse', emoji: '🌀', zone: 'daylight' },
  { name: 'Jellyfish', emoji: '🪼', zone: 'daylight' },
  { name: 'Crab', emoji: '🦀', zone: 'daylight' },
  { name: 'Lobster', emoji: '🦞', zone: 'daylight' },
  { name: 'Shrimp', emoji: '🦐', zone: 'daylight' },
  { name: 'Octopus', emoji: '🐙', zone: 'daylight' },
  { name: 'Squid', emoji: '🦑', zone: 'daylight' },
  { name: 'Sea Lion', emoji: '🦁', zone: 'daylight' },
  { name: 'Seal', emoji: '🦭', zone: 'daylight' },
  { name: 'Great White Shark', emoji: '🦈', zone: 'daylight' },
  { name: 'Whale Shark', emoji: '🐳', zone: 'daylight' },
  { name: 'Manta Ray', emoji: '🌊', zone: 'daylight' },
  { name: 'Parrotfish', emoji: '🦜', zone: 'daylight' },
  { name: 'Pufferfish', emoji: '🐡', zone: 'daylight' },
  { name: 'Lionfish', emoji: '🔥', zone: 'daylight' },
  { name: 'Moray Eel', emoji: '🐍', zone: 'daylight' },
  { name: 'Clam', emoji: '🐚', zone: 'daylight' },
  { name: 'Oyster', emoji: '💎', zone: 'daylight' },
  { name: 'Sea Cucumber', emoji: '🥒', zone: 'daylight' },
  { name: 'Sea Urchin', emoji: '🌺', zone: 'daylight' },
  { name: 'Anemone', emoji: '🌸', zone: 'daylight' },
  { name: 'Flying Fish', emoji: '✈️', zone: 'daylight' },
  { name: 'Sailfish', emoji: '⛵', zone: 'daylight' },
  { name: 'Barracuda', emoji: '⚡', zone: 'daylight' },
  { name: 'Tuna', emoji: '🐟', zone: 'daylight' },
  { name: 'Mackerel', emoji: '💨', zone: 'daylight' },
  { name: 'Herring', emoji: '🐠', zone: 'daylight' },
  { name: 'Swordfish', emoji: '⚔️', zone: 'daylight' },
  { name: 'Hammerhead Shark', emoji: '🔨', zone: 'daylight' },
  { name: 'Mahi-Mahi', emoji: '🌈', zone: 'daylight' },
  { name: 'Flounder', emoji: '🎭', zone: 'daylight' },
  { name: 'Sea Bass', emoji: '🎸', zone: 'daylight' },
  { name: 'Grouper', emoji: '🪨', zone: 'daylight' },
  { name: 'Coral', emoji: '🪸', zone: 'daylight' },
];

export const TWILIGHT_ANIMALS: BadgeAnimal[] = [
  { name: 'Lanternfish', emoji: '🔦', zone: 'twilight' },
  { name: 'Hatchetfish', emoji: '🪓', zone: 'twilight' },
  { name: 'Viperfish', emoji: '☠️', zone: 'twilight' },
  { name: 'Bristlemouth', emoji: '👄', zone: 'twilight' },
  { name: 'Flashlight Fish', emoji: '💡', zone: 'twilight' },
  { name: 'Firefly Squid', emoji: '✨', zone: 'twilight' },
  { name: 'Oarfish', emoji: '👑', zone: 'twilight' },
  { name: 'Giant Squid', emoji: '🦑', zone: 'twilight' },
  { name: 'Nautilus', emoji: '🌀', zone: 'twilight' },
  { name: 'Fangtooth Fish', emoji: '🦷', zone: 'twilight' },
  { name: 'Dragonfish', emoji: '🐉', zone: 'twilight' },
  { name: 'Cookiecutter Shark', emoji: '🍪', zone: 'twilight' },
  { name: 'Megamouth Shark', emoji: '👁️', zone: 'twilight' },
  { name: 'Stoplight Loosejaw', emoji: '🚦', zone: 'twilight' },
  { name: 'Medusafish', emoji: '🏛️', zone: 'twilight' },
  { name: 'Saber-toothed Viper Fish', emoji: '🗡️', zone: 'twilight' },
  { name: 'Pomfret', emoji: '🌑', zone: 'twilight' },
  { name: 'Deep Sea Jellyfish', emoji: '🌙', zone: 'twilight' },
  { name: 'Comb Jelly', emoji: '🔮', zone: 'twilight' },
  { name: 'Siphonophore', emoji: '🧬', zone: 'twilight' },
  { name: 'Arrow Squid', emoji: '🏹', zone: 'twilight' },
  { name: 'Bigfin Squid', emoji: '🌊', zone: 'twilight' },
  { name: 'Dumbo Octopus', emoji: '🐘', zone: 'twilight' },
  { name: 'Glass Squid', emoji: '🔍', zone: 'twilight' },
  { name: 'Deep Sea Shrimp', emoji: '🩷', zone: 'twilight' },
  { name: 'Sergestid Shrimp', emoji: '💫', zone: 'twilight' },
  { name: 'Krill', emoji: '🦐', zone: 'twilight' },
  { name: 'Moon Jellyfish', emoji: '🌕', zone: 'twilight' },
  { name: "Lion's Mane Jellyfish", emoji: '🦁', zone: 'twilight' },
  { name: "Portuguese Man o' War", emoji: '⚔️', zone: 'twilight' },
  { name: 'Blue Button Jellyfish', emoji: '💙', zone: 'twilight' },
  { name: 'Pearlfish', emoji: '💎', zone: 'twilight' },
  { name: 'Opah', emoji: '🌈', zone: 'twilight' },
  { name: 'Escolar', emoji: '🎭', zone: 'twilight' },
  { name: 'Ribbonfish', emoji: '🎀', zone: 'twilight' },
  { name: 'Ghostpipefish', emoji: '👻', zone: 'twilight' },
  { name: 'Deep Sea Copepod', emoji: '🔬', zone: 'twilight' },
  { name: 'Amphipod', emoji: '🦟', zone: 'twilight' },
  { name: 'Bristlestar', emoji: '💫', zone: 'twilight' },
  { name: 'Sabertooth Fish', emoji: '🗡️', zone: 'twilight' },
];

export const MIDNIGHT_ANIMALS: BadgeAnimal[] = [
  { name: 'Anglerfish', emoji: '🎣', zone: 'midnight' },
  { name: 'Vampire Squid', emoji: '🧛', zone: 'midnight' },
  { name: 'Zombie Worm', emoji: '🪱', zone: 'midnight' },
  { name: 'Giant Isopod', emoji: '🦠', zone: 'midnight' },
  { name: 'Sea Spider', emoji: '🕷️', zone: 'midnight' },
  { name: 'Yeti Crab', emoji: '🧊', zone: 'midnight' },
  { name: 'Frilled Shark', emoji: '🌿', zone: 'midnight' },
  { name: 'Goblin Shark', emoji: '👺', zone: 'midnight' },
  { name: 'Bluntnose Sixgill Shark', emoji: '😈', zone: 'midnight' },
  { name: 'Deep Sea Dragonfish', emoji: '🐉', zone: 'midnight' },
  { name: 'Black Swallower', emoji: '⚫', zone: 'midnight' },
  { name: 'Pelican Eel', emoji: '👄', zone: 'midnight' },
  { name: 'Sea Pig', emoji: '🐷', zone: 'midnight' },
  { name: 'Cusk Eel', emoji: '🌑', zone: 'midnight' },
  { name: 'Grenadier Fish', emoji: '💣', zone: 'midnight' },
  { name: 'Snailfish', emoji: '🐌', zone: 'midnight' },
  { name: 'Barreleye Fish', emoji: '👀', zone: 'midnight' },
  { name: 'Blobfish', emoji: '😢', zone: 'midnight' },
  { name: 'Faceless Cusk', emoji: '😶', zone: 'midnight' },
  { name: 'Spookfish', emoji: '👻', zone: 'midnight' },
  { name: 'Deep Sea Cucumber', emoji: '🥒', zone: 'midnight' },
  { name: 'Glass Sponge', emoji: '💎', zone: 'midnight' },
  { name: 'Sea Angel', emoji: '😇', zone: 'midnight' },
  { name: 'Sea Devil', emoji: '😈', zone: 'midnight' },
  { name: 'Terrible Claw Lobster', emoji: '💀', zone: 'midnight' },
  { name: 'Hydrothermal Vent Worm', emoji: '🌋', zone: 'midnight' },
  { name: 'Pompeii Worm', emoji: '🔥', zone: 'midnight' },
  { name: 'Scale Worm', emoji: '🛡️', zone: 'midnight' },
  { name: 'Deep Sea Urchin', emoji: '🦔', zone: 'midnight' },
  { name: 'Ghost Shark', emoji: '👻', zone: 'midnight' },
  { name: 'Chimaera', emoji: '🦄', zone: 'midnight' },
  { name: 'Ratfish', emoji: '🐀', zone: 'midnight' },
  { name: 'Abyssal Grenadier', emoji: '🌑', zone: 'midnight' },
  { name: 'Deep Sea Tripodfish', emoji: '🕸️', zone: 'midnight' },
  { name: 'Sixgill Hagfish', emoji: '😱', zone: 'midnight' },
  { name: 'Zombie Starfish', emoji: '⭐', zone: 'midnight' },
  { name: 'Sea Pen', emoji: '🖊️', zone: 'midnight' },
  { name: 'Fanfin Anglerfish', emoji: '🎣', zone: 'midnight' },
  { name: 'Whipnose Angler', emoji: '🎭', zone: 'midnight' },
  { name: 'Pacific Viperfish', emoji: '🌊', zone: 'midnight' },
];

export const ZONE_ANIMALS: Record<string, BadgeAnimal[]> = {
  daylight: DAYLIGHT_ANIMALS,
  twilight: TWILIGHT_ANIMALS,
  midnight: MIDNIGHT_ANIMALS,
};
